version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xpectrum-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=AKIAZKY542Z6FSTWFY26
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1
      - PORT=8000
      - AWS_SECRETS_MANAGER_ID=${AWS_SECRETS_MANAGER_ID}
    volumes:
      - ./backend/tmp:/tmp
    networks:
      - xpectrum-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xpectrum-frontend
    restart: unless-stopped
    ports:
      - "8083:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
      - VITE_WS_URL=ws://localhost:8083/api/ws/audio
    networks:
      - xpectrum-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  xpectrum-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16