services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xpectrum-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    networks:
      - xpectrum-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xpectrum-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/test-aws"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - xpectrum-network

networks:
  xpectrum-network:
    driver: bridge